services:
  python:
    build: ./Python
    restart: always
    ports:
      - "8400:8400"
      - "8401:8401"
      - "8080:8080"
      - "5678:5678"
    networks: 
      - orchestrator 



  redis:
    image: "redis:8.0.3"
    restart: always
    ports: 
      - "6379:6379"
    networks: 
      - orchestrator

      
  orchestrator:
    build: . 
    restart: always
    ports: 
      - "5100:5100"
    networks:
      - orchestrator



networks:
   orchestrator:

